service: serverless-transcribe-and-log

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  environment:
    S3_AUDIO_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-audio-records
    S3_TRANSCRIPTION_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-transcriptions
    LANGUAGE_CODE: en-US
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_AUDIO_BUCKET}/*'
        - 'arn:aws:s3:::${self:provider.environment.S3_TRANSCRIPTION_BUCKET}/*'
    - Effect: Allow
      Action:
        - transcribe:StartTranscriptionJob
      Resource: '*'

functions:
  transcribe:
    handler: handlers/transcribe.transcribe
    events:
      - s3:
          bucket: ${self:provider.environment.S3_AUDIO_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp3
  log:
    handler: handlers/log.log
    events:
      - s3:
          bucket: ${self:provider.environment.S3_TRANSCRIPTION_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json


# resources:
#   Resources:
#     S3TranscriptionBucket:
#       Type: 'AWS::S3::Bucket'
#       Properties:
#         BucketName: ${self:provider.environment.S3_TRANSCRIPTION_BUCKET}
